name: Build and Publish SanityScrew

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y cmake g++-multilib libboost-all-dev

    - name: Find and change to src directory
      run: cd $(find $GITHUB_WORKSPACE -type d -name src)

    - name: Generate random tag
      id: tag
      run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)"

    - name: Compile for ${{ matrix.arch }}
      run: |
        cd src
        make .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.arch }}
        path: ./src

    - name: Publish release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: src/*
        tag_name: ${{ steps.tag.outputs.tag }}
        token: ${{ secrets.TOKEN }}

    - name: Clean up
      run: rm -rf build-${{ matrix.arch }}
