name: Build and Publish SanityScrew

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch: [x32, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-all-dev
        sudo apt-mark hold grub*

    - name: Setup Boost
      run: sudo apt-get install -y libboost-all-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Generate CMake files
      run: cmake -S . -B build

    - name: Build SanityScrew
      run: |
        cd build
        cmake --build .

    - name: Archive build artifacts
      run: |
        mkdir -p artifacts
        cp build/SanityScrew artifacts/
      if: success()

    - name: Create a tag and release
      id: create_tag
      run: |
        TAG=v0.1.$(date +%s)
        echo "TAG=$TAG" >> $GITHUB_ENV
        git tag $TAG
        git push origin $TAG

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        tag: ${{ env.TAG }}
        name: Release ${{ env.TAG }}
        files: artifacts/SanityScrew
