name: Build and Publish SanityScrew

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-all-dev
        sudo apt-mark hold grub*

    - name: Setup Boost
      run: sudo apt-get install -y libboost-all-dev

    - name: Cd into Source DIR
      run: cd src

    - name: Generate CMake files
      run: cd src && cmake -S .

    - name: Build SanityScrew
      run: |
        cd src
        cmake --build .

    - name: Archive build artifacts
      run: |
        mkdir -p artifacts
        cp -r . artifacts/ & cp -r src/*  artifacts/
      if: success()

    - name: Create Tag And Release
  # You may pin to the exact commit or the version.
  # uses: gabrielogregorio/create-tag-and-release@06a33f35d4e41ed83ea18c48bf012e1f6d79950f
      uses: gabrielogregorio/create-tag-and-release@v1.0.0
        with:
    # The name of the tag.
    tag_name: v1.0.0
    # The name of the release.
    release_name: v1.0.0
    # body of release
    body: # optional
    # file that will contain the release body. If informed, body will be disregarded
    body_path: # optional
    # true to create a draft (unpublished) release, false to create a published one. Default: false
    draft: # optional
    # true to identify the release as a prerelease. false to identify the release as a full release. Padrão: false
    prerelease: # optional
    # Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
    target_commitish: # optional
    # The account owner of the repository. The name is not case sensitive.
    owner: # optional
    # The name of the repository without the .git extension. The name is not case sensitive.
    repo: # optional
    # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "Managing categories for discussions in your repository."
    discussion_category_name: # optional
    # Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes. Padrão: false
    generate_release_notes: # optional
    # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to true for newly published releases. legacy specifies that the latest release should be determined based on the release creation date and higher semantic version. Padrão: true
    make_latest: true
          

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        tag: ${{ env.TAG }}
        name: Release ${{ env.TAG }}
        files: artifacts/SanityScrew
